apiVersion: apps/v1
kind: Deployment
metadata:
  name: garden-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: garden-api
  template:
    metadata:
      labels:
        app: garden-api
    spec:
      containers:
        - name: garden-api
          image: garden-api:latest
          ports:
            - containerPort: 8080