apiVersion: v1
kind: ConfigMap
metadata:
  name: garden-config
data:
  Jwt__Issuer: Garden.Api
  Jwt__Audience: Garden.App
  ConnectionStrings__GardenDb: "Server=garden-sqlserver,1433;Database=GardenDb;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;"