apiVersion: apps/v1
kind: Deployment
metadata:
  name: garden-api
spec:
  template:
    spec:
      containers:
        - name: garden-api
          envFrom:
            - configMapRef:
                name: garden-config
            - secretRef:
                name: garden-secrets