apiVersion: v1
kind: Secret
metadata:
  name: garden-secrets
type: Opaque
stringData:
  Jwt__Key: "CHANGE_ME"
  MSSQL_SA_PASSWORD: "CHANGE_ME"
  ConnectionStrings__GardenDb: "Server=garden-sqlserver,1433;Database=GardenDb;User Id=sa;Password=CHANGE_ME;TrustServerCertificate=True;"